# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.14.2
_src_path: gh:oca/oca-addons-repo-template
ci: GitHub
dependency_installation_mode: PIP
generate_requirements_txt: true
github_check_license: true
github_ci_extra_env: {}
github_enable_codecov: true
github_enable_makepot: true
github_enable_stale_action: true
github_enforce_dev_status_compatibility: true
include_wkhtmltopdf: false
odoo_version: 14.0
org_name: Odoo Community Association (OCA)
org_slug: OCA
rebel_module_groups:
- resource_booking_simultaneous_human
repo_description: Modules that extend Odoo calendar management tools
repo_name: Calendar modules for Odoo
repo_slug: calendar
repo_website: https://github.com/OCA/calendar
travis_apt_packages: []
travis_apt_sources: []

